# Generated by Django 5.1.1 on 2025-07-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickcheckpack',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
