# Generated by Django 5.1.1 on 2025-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_pickcheckpack_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickcheckpack',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked', 'Picked'), ('checked', 'Checked'), ('packed', 'Packed')], max_length=10, null=True),
        ),
    ]
