# Generated by Django 5.1.1 on 2025-07-13 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_pickcheckpack_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assined', 'Assigned'), ('started', 'Started'), ('completed', 'Completed')], default='placed', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
