# Generated by Django 5.1.1 on 2025-07-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
