# Generated by Django 5.1.1 on 2025-07-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_is_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
