# Generated by Django 5.1.1 on 2025-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
