# Generated by Django 5.1.1 on 2025-07-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_cgst_inventory_igst_inventory_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='dis_scheme',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
