# Generated by Django 5.1.1 on 2025-07-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_dis_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
