# Generated by Django 5.1.1 on 2025-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
