# Generated by Django 5.1.1 on 2025-07-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordercart_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercart',
            old_name='user',
            new_name='customer',
        ),
    ]
