# Generated by Django 5.1.1 on 2025-07-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_checked_at_orders_checker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='checked_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='packed_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='packer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='picked_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='picker',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='picker_at',
        ),
    ]
