# Generated by Django 5.1.1 on 2025-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orders_checked_at_remove_orders_checker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('packed', 'Packed'), ('picked', 'Picked'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_initiated', 'Return Initiated'), ('return_received', 'Return Received'), ('refunded', 'Refunded')], default='placed', max_length=20),
        ),
    ]
