# Generated by Django 5.1.1 on 2025-07-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_duty'),
        ('orders', '0009_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_duty', to='logistics.duty'),
        ),
    ]
